/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cheques;

import Controlador.Cuenta_sql;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Byrich
 */
public class Bloquear extends javax.swing.JPanel {
    Cuenta_sql api;
    public String idOperador;
    /**
     * Creates new form PedirChequera
     */
    public Bloquear() {
        initComponents();
        ncuenta.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                int key = (int)e.getKeyChar();
                if (!(key < 58 && key > 47)) {
                    ncuenta.setText("");
                }
            }
        });
        ncheque.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                int key = (int)e.getKeyChar();
                if (!(key < 58 && key > 47)) {
                    ncheque.setText("");
                }
            }
        });
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ncuenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ncheque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jButton1.setText("Bloquear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("No. Cueta");

        jLabel2.setText("No. Cheque");

        jButton2.setText("Robado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Extraviado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Extraviado");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ncheque, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(135, 135, 135)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ncheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton3)
                .addGap(33, 33, 33)
                .addComponent(jButton4)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String actual = ncuenta.getText();
        String actual1 = ncheque.getText();
        if (actual.isEmpty() || actual1.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ningun campo debe estar vacio");
        }
        else{
            int ret = api.bloquear(actual,actual1, "1");
            if (ret == 1){
                JOptionPane.showMessageDialog(null, "cheque bloqueado");
            }
            else if (ret == -2){
                JOptionPane.showMessageDialog(null, "El cheque: " +actual1+ " no existe o ya fue cobrado");
            }
            else if (ret == -3){
                JOptionPane.showMessageDialog(null, "La cuenta : " +actual+ " no existe");
            }
            else{
                JOptionPane.showMessageDialog(null, "Intente mas tarde");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String actual = ncuenta.getText();
        String actual1 = ncheque.getText();
        if (actual.isEmpty() || actual1.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ningun campo debe estar vacio");
        }
        else{
            int ret = api.bloquear(actual,actual1, "2");
            if (ret == 1){
                JOptionPane.showMessageDialog(null, "cheque reportado por robo");
            }
            else if (ret == -2){
                JOptionPane.showMessageDialog(null, "El cheque: " +actual1+ " no existe o ya fue cobrado");
            }
            else if (ret == -3){
                JOptionPane.showMessageDialog(null, "La cuenta : " +actual+ " no existe");
            }
            else{
                JOptionPane.showMessageDialog(null, "Intente mas tarde");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String actual = ncuenta.getText();
        String actual1 = ncheque.getText();
        if (actual.isEmpty() || actual1.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ningun campo debe estar vacio");
        }
        else{
            int ret = api.bloquear(actual,actual1, "0");
            if (ret == 1){
                JOptionPane.showMessageDialog(null, "cheque reportado por extraviado");
            }
            else if (ret == -2){
                JOptionPane.showMessageDialog(null, "El cheque: " +actual1+ " no existe o ya fue cobrado");
            }
            else if (ret == -3){
                JOptionPane.showMessageDialog(null, "La cuenta : " +actual+ " no existe");
            }
            else{
                JOptionPane.showMessageDialog(null, "Intente mas tarde");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String actual = ncuenta.getText();
        String actual1 = ncheque.getText();
        if (actual.isEmpty() || actual1.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ningun campo debe estar vacio");
        }
        else{
            int ret = api.bloquear(actual,actual1, "3");
            if (ret == 1){
                JOptionPane.showMessageDialog(null, "cheque desbloquado");
            }
            else if (ret == -2){
                JOptionPane.showMessageDialog(null, "El cheque: " +actual1+ " no existe o ya fue cobrado");
            }
            else if (ret == -3){
                JOptionPane.showMessageDialog(null, "La cuenta : " +actual+ " no existe");
            }
            else{
                JOptionPane.showMessageDialog(null, "Intente mas tarde");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public void cargarApi(Cuenta_sql papa){
        this.api = papa;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField ncheque;
    private javax.swing.JTextField ncuenta;
    // End of variables declaration//GEN-END:variables
}
